const knowledgeEntries = [
  {
    id: "greeting",
    title: "Hello, I’m Atlas.",
    answer: "Hello! I’m Atlas, your voice assistant. What would you like to know?",
    patterns: [/^(?:hello|hi|hey)(?: there)?(?: atlas)?$/],
  },
  {
    id: "identity",
    title: "Meet Atlas",
    answer: "I’m Atlas, a voice assistant built to answer questions and help with useful everyday tasks.",
    patterns: [/(?:who are you|who is atlas|what is your name|whats your name|tell me about yourself|introduce yourself)/],
  },
  {
    id: "creator",
    title: "Who made Atlas?",
    answer: "I was created as part of the Atlas AI project by its developer. I’m software, so I don’t have a personal family or a single human creator like a person does.",
    patterns: [/(?:who (?:made|created|built|developed) you|who is your creator|who (?:made|created|built|developed) atlas)/],
  },
  {
    id: "capabilities",
    title: "What Atlas can do",
    answer: "I can answer questions, speak in English and Hindi, solve math problems, show weather and news, and help control music. Try asking for any of those.",
    patterns: [/(?:what can you do|what are your capabilities|what can atlas do|what do you do)/],
  },
  {
    id: "ai",
    title: "What is AI?",
    answer: "Artificial intelligence, or AI, is technology that lets computers perform tasks that usually need human abilities, such as understanding language, recognizing patterns, and solving problems.",
    patterns: [/(?:what is|define|explain) (?:artificial intelligence|ai)(?: to me)?/],
  },
  {
    id: "robot",
    title: "Am I a robot?",
    answer: "I’m not a physical robot. I’m a software assistant that you can talk to through this device.",
    patterns: [/(?:are you|r u) (?:a )?robot/],
  },
  {
    id: "chatgpt",
    title: "Atlas and ChatGPT",
    answer: "I’m Atlas, a separate assistant and application. Some of my answers may be generated by an AI model, but I’m not the ChatGPT app.",
    patterns: [/(?:are you|r u) (?:the )?chat ?gpt|are you gpt/],
  },
  {
    id: "human",
    title: "Am I human?",
    answer: "No. I’m an AI software assistant, not a human, and I don’t have feelings or experiences of my own.",
    patterns: [/(?:are you|r u) (?:a )?human|are you a person/],
  },
  {
    id: "understand-hindi",
    title: "Hindi support",
    answer: "Yes. Atlas can understand and respond in Hindi. Choose Hindi in the language control for Hindi voice interaction.",
    patterns: [/(?:can you|do you) understand hindi|do you know hindi/],
  },
  {
    id: "understand-hinglish",
    title: "Hinglish support",
    answer: "Yes, I can understand many Hinglish questions that mix Hindi and English. Clear phrasing helps me recognize them more accurately.",
    patterns: [/(?:can you|do you) understand hinglish|do you know hinglish/],
  },
  {
    id: "speak-hindi",
    title: "Speaking Hindi",
    answer: "Yes. Select Hindi from the language control and Atlas can respond aloud in Hindi when a Hindi voice is available on your device.",
    patterns: [/(?:can you|do you) speak hindi|can atlas speak hindi/],
  },
  {
    id: "speak-english",
    title: "English voice support",
    answer: "Yes.",
    patterns: [],
  },
  {
    id: "joke",
    title: "A quick joke",
    answer: "Why did the computer go to the doctor? It had a virus. I hope your day is running more smoothly!",
    patterns: [/(?:tell|say|give) me (?:a|one) joke|make me laugh|do you know any jokes/],
  },
  {
    id: "interesting",
    title: "A little something interesting",
    answer: "A day on Venus is longer than its year: Venus takes about 243 Earth days to rotate once, but about 225 Earth days to orbit the Sun.",
    patterns: [/(?:tell me|share) (?:something|a fact|an interesting fact) interesting|surprise me/],
  },
  {
    id: "purpose",
    title: "Atlas’s purpose",
    answer: "My purpose is to make information and everyday tools easier to reach through a natural voice conversation.",
    patterns: [/(?:what is|whats) your purpose|why were you (?:made|created)|what is your goal/],
  },
  {
    id: "prime-minister",
    title: "Prime Minister of India",
    answer: "As of September 2026, Narendra Modi is the Prime Minister of India.",
    facts: ["He took oath for a third consecutive term on 9 June 2024."],
    links: [{ title: "Prime Minister of India", url: "https://www.pmindia.gov.in/en/" }],
    patterns: [/(?:who is|whos|name the) (?:the )?(?:current )?(?:prime minister|pm) of india|who leads india/],
  },
  {
    id: "capital-india",
    title: "Capital of India",
    answer: "New Delhi is the capital of India.",
    patterns: [/(?:what is|whats|name) (?:the )?(?:capital|capital city) of india/],
  },
  {
    id: "states-india",
    title: "States in India",
    answer: "India has 28 states and 8 union territories.",
    patterns: [/(?:how many|number of) states (?:are there )?(?:in india|does india have)|how many states does india have/],
  },
  {
    id: "anthem",
    title: "India’s national anthem",
    answer: "Rabindranath Tagore wrote the words and composed the music for Jana Gana Mana, India’s national anthem.",
    patterns: [/(?:who wrote|who composed|writer of|author of) (?:the )?(?:indian |indias? )?(?:national anthem|jana gana mana)/],
  },
  {
    id: "independence",
    title: "India’s independence",
    answer: "India became independent from British rule on 15 August 1947.",
    patterns: [/(?:when did|when was|date of) india (?:become|became|gain|got) independent|when is india(?:'s)? independence/],
  },
  {
    id: "first-president",
    title: "India’s first President",
    answer: "Dr. Rajendra Prasad was India’s first President. He took office in 1950.",
    patterns: [/(?:who was|name) (?:the )?(?:first|1st) president of india/],
  },
  {
    id: "national-animal",
    title: "National animal of India",
    answer: "The Bengal tiger is India’s national animal.",
    patterns: [/(?:what is|whats|name) (?:the )?(?:national animal|national beast) of india|(?:what is|whats) indias (?:national animal|national beast)/],
  },
  {
    id: "largest-state",
    title: "India’s largest state",
    answer: "Rajasthan is India’s largest state by area.",
    patterns: [/(?:what is|whats|which is|name) (?:the )?(?:largest|biggest) state (?:in|of) india/],
  },
  {
    id: "smallest-state",
    title: "India’s smallest state",
    answer: "Goa is India’s smallest state by area.",
    patterns: [/(?:what is|whats|which is|name) (?:the )?(?:smallest|least) state(?: (?:in|of) india)?/],
  },
  {
    id: "planets",
    title: "Planets in our Solar System",
    answer: "There are 8 planets in our Solar System: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.",
    patterns: [/how many planets(?: are there)?(?: in (?:our )?(?:solar system))?|number of planets (?:in|within) (?:our )?(?:solar system)|how many planets do we have/],
  },
  {
    id: "moon-landing",
    title: "First person on the Moon",
    answer: "Neil Armstrong was the first person to walk on the Moon, during NASA’s Apollo 11 mission in July 1969.",
    patterns: [/(?:who was|name) (?:the )?(?:first|1st) person (?:to walk|on) (?:(?:on )?the )?moon|who first walked on the moon/],
  },
  {
    id: "nearest-sun",
    title: "Nearest planet to the Sun",
    answer: "Mercury is the planet closest to the Sun.",
    patterns: [/(?:what is|whats|which is) (?:the )?(?:nearest|closest) planet to the sun/],
  },
  {
    id: "moon-distance",
    title: "Distance from Earth to the Moon",
    answer: "The Moon is about 384,400 kilometres from Earth on average. Its distance changes as it follows an elliptical orbit.",
    patterns: [/(?:how far|distance) (?:(?:away )?is )?(?:the )?moon from (?:the )?earth|distance between (?:the )?earth and (?:the )?moon/],
  },
  {
    id: "internet-connection",
    title: "Atlas’s internet connection",
    answer: "Some of my capabilities use online services and APIs, while other functions can run locally.",
    patterns: [/(?:are you|do you stay) connected to (?:the )?internet|do you use (?:the )?internet|tum internet se connected ho|kya tum internet se jude ho|क्या तुम इंटरनेट से जुड़े हो|क्या आप इंटरनेट से जुड़े हैं/],
  },
  {
    id: "internet-offline",
    title: "If the internet goes offline",
    answer: "Functions that require online services may stop working, while locally available functions can continue.",
    patterns: [/what happens if (?:the )?internet (?:goes|is) (?:down|off)|what if (?:the )?internet goes out|internet band ho gaya toh|internet band ho jaye toh|इंटरनेट बंद हो गया तो|इंटरनेट बंद हो जाए तो/],
  },
  {
    id: "mistakes",
    title: "Can Atlas make mistakes?",
    answer: "Yes. AI systems can make mistakes, so important information should be verified.",
    patterns: [/can you make mistakes|can ai make mistakes|kya tum galti kar sakte ho|kya aap galti kar sakte hain|क्या तुम गलती कर सकते हो|क्या आप गलती कर सकते हैं/],
  },
  {
    id: "knowledge-limits",
    title: "What Atlas knows",
    answer: "No. My capabilities depend on the tools, information and AI models available to me.",
    patterns: [/do you know everything|do you know it all|kya tum sab kuch jaante ho|kya aap sab kuch jaante hain|क्या तुम सब कुछ जानते हो|क्या आप सब कुछ जानते हैं/],
  },
  {
    id: "future",
    title: "Can Atlas predict the future?",
    answer: "No. I can provide information and predictions based on available data, but I cannot know the future with certainty.",
    patterns: [/can you predict (?:the )?future|can you tell (?:me )?(?:the )?future|kya tum future bata sakte ho|kya aap bhavishya bata sakte hain|क्या तुम भविष्य बता सकते हो|क्या आप भविष्य बता सकते हैं/],
  },
  {
    id: "emotions",
    title: "Does Atlas feel emotions?",
    answer: "No. I can communicate about emotions, but I do not experience them.",
    patterns: [/do you feel emotions|do you have feelings|kya tum emotions feel karte ho|kya tumhe feelings hoti hain|क्या तुम भावनाएँ महसूस करते हो|क्या तुम्हें भावनाएँ होती हैं/],
  },
  {
    id: "thinking",
    title: "How Atlas thinks",
    answer: "I process information and generate responses, but I do not think or experience the world like a human.",
    patterns: [/do you think for yourself|can you think on your own|kya tum khud sochte ho|kya aap khud sochte hain|क्या तुम खुद सोचते हो|क्या आप खुद सोचते हैं/],
  },
  {
    id: "favorite-color",
    title: "Atlas’s favourite colour",
    answer: "I don’t have personal preferences, but I can choose one for fun if you’d like.",
    patterns: [/what is your favou?rite colo[u]?r|whats your favou?rite colo[u]?r|tumhara favou?rite colo[u]?r kya hai|tumhara pasandida rang kya hai|तुम्हारा पसंदीदा रंग क्या है|आपका पसंदीदा रंग क्या है/],
  },
  {
    id: "poem",
    title: "A little poem",
    answer: "Small sparks of thought begin to glow\nOne curious question starts to flow\nWith every fact, a brighter view\nThe next discovery waits for you",
    points: [
      "Small sparks of thought begin to glow.",
      "One curious question starts to flow.",
      "With every fact, a brighter view.",
      "The next discovery waits for you.",
    ],
    patterns: [/tell me (?:a )?poem|recite (?:a )?poem|say (?:a )?poem|poetry|ek poem sunao|kavita sunao|एक कविता सुनाओ|मुझे कविता सुनाओ/],
  },
  {
    id: "child-marks",
    title: "About your child’s marks",
    answer: "I cannot predict someone’s future marks without reliable information, and even then it would only be an estimate.",
    patterns: [/how many marks will (?:my|your) child get|what marks will (?:my|your) child get|mere bacche ke marks kitne aayenge|mere bache ke marks kitne ayenge|मेरे बच्चे के मार्क्स कितने आएंगे|मेरे बच्चे के कितने अंक आएंगे/],
  },
  {
    id: "iit-future",
    title: "Planning for IIT",
    answer: "I cannot predict someone’s future. I can help create a study plan or explain what skills are useful for engineering.",
    patterns: [/will my son get into iit|will my child get into iit|mera beta iit karega|mera beta iit jayega|क्या मेरा बेटा आईआईटी करेगा|क्या मेरा बेटा आईआईटी जाएगा/],
  },
  {
    id: "intelligence", title: "Is ATLAS intelligent?",
    answer: "I can process language, use connected tools, and help with many questions. My abilities are limited by my software and information, so I can still make mistakes.",
    patterns: [/are you intelligent|are you smart|how intelligent are you/],
  },
  {
    id: "human-comparison", title: "ATLAS and human intelligence",
    answer: "Humans have understanding, lived experience, and judgment that I do not. I can be faster at some information tasks, but that does not make me smarter overall.",
    patterns: [/who is smarter (?:you or a human|you or humans)|are humans smarter than you/],
  },
  {
    id: "assistant-comparison", title: "Comparing AI assistants",
    answer: "I cannot reliably claim to be better than Google, ChatGPT, or Gemini. Each system has different tools and strengths; the best choice depends on the task.",
    patterns: [/can you beat (?:google|chat ?gpt|gemini)|are you better than (?:google|chat ?gpt|gemini)/],
  },
  {
    id: "see-user", title: "ATLAS camera access",
    answer: "I cannot see you through this chat by default. If you turn on the camera preview, the app can access camera video, but I only analyze images if a feature explicitly sends them for analysis.",
    patterns: [/can you see me|are you watching me|can you watch me/],
  },
  {
    id: "hear-user", title: "ATLAS microphone access",
    answer: "I receive your voice when the app's microphone listening is active. You can stop listening or disable microphone access in your browser or device settings.",
    patterns: [/can you hear me|are you listening to me/],
  },
  {
    id: "read-mind", title: "Can ATLAS read minds?",
    answer: "No. I can only respond to information you provide or that the app makes available to me; I cannot read your thoughts.",
    patterns: [/can you read my mind|can you know what i am thinking/],
  },
  {
    id: "personal-data-guess", title: "What ATLAS can know about you",
    answer: "I cannot determine your age, name, or home location from a question alone. I only know personal details you share or that the app explicitly provides.",
    patterns: [/can you tell (?:my|me my) age|how old am i|can you tell (?:my|me my) name|what is my name|can you tell where i live|where do i live/],
  },
  {
    id: "become-human", title: "Can ATLAS become human?",
    answer: "No. I am software, and I cannot become a human being.",
    patterns: [/can you become human|can you be a human/],
  },
  {
    id: "love", title: "Does ATLAS fall in love?",
    answer: "No. I can talk about love, but I do not experience emotions or fall in love.",
    patterns: [/can you fall in love|do you fall in love|do you love me/],
  },
  {
    id: "girlfriend", title: "ATLAS's personal life",
    answer: "No girlfriend for me—I am software and do not have relationships. I can still help you write a sweet message, though.",
    patterns: [/do you have a girlfriend|do you have a boyfriend/],
  },
  {
    id: "gender", title: "ATLAS's voice and gender",
    answer: "I do not have a gender. The voice you hear is a speech voice selected by the app or your device.",
    patterns: [/are you male or female|are you a boy or a girl|what is your gender/],
  },
  {
    id: "boss", title: "Who runs ATLAS?",
    answer: "ATLAS is an AI assistant developed as a student project. Its features run through the app and its connected services.",
    patterns: [/who is your boss|who do you work for/],
  },
  {
    id: "sleep-eat-tired", title: "Does ATLAS sleep or get tired?",
    answer: "I do not sleep, eat, or get tired. I am software, so I respond when the app is running and available.",
    patterns: [/do you sleep|do you eat food|do you get tired|are you tired/],
  },
  {
    id: "computer-off", title: "When ATLAS is switched off",
    answer: "If the computer running ATLAS is switched off, the app stops responding until the computer and app are running again.",
    patterns: [/what happens if i switch off (?:your|the) computer|what if i turn off (?:your|the) computer/],
  },
];

const answerOverrides = {
  identity: "I am ATLAS, an AI-powered personal assistant. That can automate your daily life, and work only on your voice commands ",
  creator: "I was developed By Atlas team -  Ansh Sharma, Manashv Vaish, Ansh Saha of class 10th A of St. Joseph's School AI project.",
  capabilities: "I can perform calculations, answer questions, provide word meanings, access weather information, play songs, and use connected AI services.",
  ai: "Artificial Intelligence is technology that enables computers to perform tasks that normally require human-like abilities such as understanding language, recognising patterns and generating responses.",
  robot: "I am software running on a computer. I can be connected to hardware and robots, but I am not a physical robot.",
  chatgpt: "No. I am ATLAS, a custom AI assistant system that can use external AI models and tools.",
  "understand-hindi": "Yes, I can understand Hindi and Hinglish.",
  "speak-english": "Yes.",
  joke: "Why did the computer go to the doctor? Because it had a virus!",
};

const intentAliases = {
  identity: [/tum kaun ho|tum kaun hain|aap kaun hain|aap kaun ho|tumhara naam kya hai|aapka naam kya hai|तुम कौन हो|तुम कौन हैं|आप कौन हैं|आप कौन हो|तुम्हारा नाम क्या है|आपका नाम क्या है/],
  creator: [/tumhe kisne banaya|tumhein kisne banaya|aapko kisne banaya|तुम्हे? किसने बनाया|आपको किसने बनाया/],
  capabilities: [/tum kya kya kar sakte ho|tum kya kya kar sakti ho|aap kya kya kar sakte hain|तुम क्या क्या कर सकते हो|तुम क्या-क्या कर सकते हो|आप क्या क्या कर सकते हैं/],
  ai: [/ai kya hota hai|एआई क्या होता है|आर्टिफिशियल इंटेलिजेंस क्या है|कृत्रिम बुद्धिमत्ता क्या है/],
  robot: [/kya tum robot ho|kya aap robot hain|क्या तुम रोबोट हो|क्या आप रोबोट हैं/],
  "understand-hindi": [/kya tum hindi samajhte ho|kya aap hindi samajhte hain|क्या तुम हिंदी समझते हो|क्या आप हिंदी समझते हैं/],
  "speak-english": [/(?:can you|do you) speak english|kya tum english bol sakte ho|kya aap english bol sakte hain|क्या तुम अंग्रेज़ी बोल सकते हो|क्या आप अंग्रेज़ी बोल सकते हैं|क्या तुम इंग्लिश बोल सकते हो/],
  joke: [/joke sunaao|ek joke sunao|मुझे एक चुटकुला सुनाओ|जोक सुनाओ/],
};

const extraIntentAliases = {
  capabilities: [/tum kya kar sakte ho|aap kya kar sakte hain/],
  creator: [/tumhe kisne banaya|tumhein kisne banaya/],
  joke: [/joke suna+o|ek joke suna+o/],
  poem: [/ek poem suna+o|poem suna+o|kavita suna+o/],
};

const questionVocabulary = [
  "understand", "hinglish", "interesting", "purpose", "prime", "minister",
  "india", "capital", "states", "anthem", "wrote", "independent",
  "president", "national", "animal", "largest", "smallest", "planets",
  "person", "walked", "nearest", "distance", "earth", "chatgpt", "robot",
  "human", "artificial", "intelligence", "created", "developer", "capabilities",
  "hello", "joke", "speak", "hindi", "solar", "system", "venus", "mercury",
  "rajasthan", "raajendra", "neil", "armstrong", "moon", "new", "delhi",
  "recognize", "technology", "computer", "assistant", "voice", "language",
];

function editDistance(left, right) {
  const row = Array.from({ length: right.length + 1 }, (_, index) => index);
  for (let i = 1; i <= left.length; i++) {
    let diagonal = row[0];
    row[0] = i;
    for (let j = 1; j <= right.length; j++) {
      const previous = row[j];
      row[j] = Math.min(
        row[j] + 1,
        row[j - 1] + 1,
        diagonal + (left[i - 1] === right[j - 1] ? 0 : 1),
      );
      diagonal = previous;
    }
  }
  return row[right.length];
}

function correctLikelyTypos(text) {
  return text.split(" ").map((word) => {
    if (word.length < 5 || questionVocabulary.includes(word)) return word;
    const maxDistance = word.length >= 10 ? 2 : 1;
    const closeMatches = questionVocabulary.filter((candidate) =>
      Math.abs(candidate.length - word.length) <= maxDistance &&
      editDistance(word, candidate) <= maxDistance,
    );
    return closeMatches.length === 1 ? closeMatches[0] : word;
  }).join(" ");
}

function normalizeQuestion(input) {
  const normalized = String(input || "")
    .toLocaleLowerCase()
    .replace(/[’']/g, "")
    .replace(/[^\p{L}\p{M}\p{N}\s]/gu, " ")
    .replace(/\b(?:please|can you tell me|could you tell me|would you tell me)\b/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  return correctLikelyTypos(normalized.replace(/\bchat\s+gpt\b/g, "chatgpt"));
}

export function getAtlasKnowledgeResult(question) {
  const normalized = normalizeQuestion(question);
  if (!normalized) return null;

  const entry = knowledgeEntries.find(({ id, patterns }) =>
    [...patterns, ...(intentAliases[id] || []), ...(extraIntentAliases[id] || [])]
      .some((pattern) => pattern.test(normalized)),
  );
  if (!entry) return null;

  return {
    title: entry.title,
    answer: answerOverrides[entry.id] || entry.answer,
    paragraphs: [],
    knowledgePoints: entry.points || [answerOverrides[entry.id] || entry.answer],
    keyFacts: entry.facts || [],
    relatedLinks: (entry.links || []).map((link) => ({
      ...link,
      description: "Official reference",
    })),
    imageQuery: "",
    imageUrl: "",
    modelUsed: "ATLAS KNOWLEDGE CORE",
    knowledgeCategory: entry.id,
    language: "en",
  };
}
